apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rso-service-ingress
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: ""
    http:
      paths:
      - backend:
          service:
            name: user-cip-service
            port:
              number: 80
        path: /users
        pathType: Prefix
      - backend:
          service:
            name: ad-cip-service
            port:
              number: 80
        path: /ads
        pathType: Prefix
      - backend:
          service:
            name: transaction-cip-service
            port:
              number: 80
        path: /transactions
        pathType: Prefix
      - backend:
          service:
            name: discussion-cip-service
            port:
              number: 80
        path: /discussions
        pathType: Prefix